engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/BooleanArgumentFlag:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/*
- c3.php
