language: php

php:
  - 5.5

branches:
  only:
    - develop

services:
  - mysql

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2"
#  - travis_retry composer update --dev --prefer-dist --no-interaction

before_script:
#  - sudo apt-get update
#  - sudo apt-get -y --reinstall install php-imagick
#  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo pecl -f imagick
  - mysql -e 'CREATE DATABASE IF NOT EXISTS seotag_test;'
  - composer update --prefer-dist --no-interaction
  - touch tests/_app/config/db.local.php
  - echo '<?php return [\'dsn\' => \'mysql:host=127.0.0.1;dbname=seotag_test\'];' => tests/_app/config/db.local.php
  - php tests/_app/yii.php migrate --interactive=0
  - vendor/bin/codecept build

script:
  - php vendor/bin/codecept run --coverage
