language: php

php:
  - 5.5

#branches:
#  only:
#    - master

services:
  - mysql

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2"
#  - travis_retry composer update --dev --prefer-dist --no-interaction

before_script:
  - sudo apt-get -y install imagemagick
#  - sudo apt-get update
#  - sudo apt-get -y --reinstall install php5-imagick
#  - pecl install -f imagick
  - printf "\n" | pecl install imagick
#  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'CREATE DATABASE IF NOT EXISTS seotag_test;'
  - composer update --prefer-dist --no-interaction
  - touch tests/_app/config/db.local.php
  - echo "<?php return ['dsn' => 'mysql:host=127.0.0.1:3306;dbname=seotag_test','username' => 'root'];" > tests/_app/config/db.local.php
  - mkdir -p tests/_envs/assets
  - mkdir tests/_app/runtime
  - php tests/_app/yii.php migrate --interactive=0
  - php tests/_app/yii.php fixture/generate pagesTemplate --count=1 --interactive=0
  - php tests/_app/yii.php fixture/generate keywordTemplate --count=16 --interactive=0
  - vendor/bin/codecept build
#  - php tests/_app/yii.php serve &

script:
  - php tests/_app/yii.php serve > /dev/null 2>&1 & php vendor/bin/codecept run --coverage --coverage-xml

addons:
  code_climate:
    repo_token: ba1056a468f20b1f15285b9f09ad49ba8ba9cefe7d3612688fd56259d8613a06

after_success:
  - vendor/bin/test-reporter --coverage-report tests/_output/coverage.xml